In [35]:
import pandas as pd

In [52]:
import pandas as pd
POI_dataDF = pd.read_csv('Silver/gold_outlet_catchment_features.csv')

In [53]:
POI_dataDF.head(10)

,Outlet_ID,Latitude,Longitude,Catchment_Schools_1km,Catchment_Hospitals_1km,Catchment_Transit_1km,Catchment_Markets_1km,Total_POIs_1km
0,OUT_00001,7.089846,79.979055,0,0,0,0,0
1,OUT_00002,7.000558,80.012422,1,0,0,0,1
2,OUT_00003,6.806170,79.854547,0,0,0,0,0
3,OUT_00004,6.703533,79.806919,0,0,0,0,0
4,OUT_00005,7.186878,79.869831,1,0,0,0,1
5,OUT_00006,6.957117,79.977724,0,0,0,0,0
6,OUT_00007,6.925250,79.803979,0,0,0,0,0
7,OUT_00008,6.852307,79.829302,0,0,0,0,0
8,OUT_00009,7.116597,79.852009,0,0,0,0,0
9,OUT_00010,6.912578,79.862382,11,5,25,1,42

In [54]:
POI_dataDF.info()

<class 'pandas.DataFrame'>
RangeIndex: 19760 entries, 0 to 19759
Data columns (total 8 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Outlet_ID                19760 non-null  str
 1   Latitude                 19760 non-null  float64
 2   Longitude                19760 non-null  float64
 3   Catchment_Schools_1km    19760 non-null  int64
 4   Catchment_Hospitals_1km  19760 non-null  int64
 5   Catchment_Transit_1km    19760 non-null  int64
 6   Catchment_Markets_1km    19760 non-null  int64
 7   Total_POIs_1km           19760 non-null  int64
dtypes: float64(2), int64(5), str(1)
memory usage: 1.2 MB

In [55]:
POI_dataDF['Total_POIs_1km'].min()

np.int64(0)

In [56]:
POI_dataDF['Total_POIs_1km'].max()

np.int64(60)

In [57]:
bins = [0, 2, 5, 10, 20, 30, 40, 50, 60]
labels = ['0-2', '2-5', '5-10', '10-20', '20-30', '30-40', '40-50', '50-60']

# Add POI_Range to original df
POI_dataDF['POI_Range'] = pd.cut(POI_dataDF['Total_POIs_1km'], bins=bins, labels=labels, right=False, include_lowest=True)

# Get Outlet_IDs per range (don't overwrite POI_dataDF)
range_outlets = POI_dataDF.groupby('POI_Range')['Outlet_ID'].apply(list).reset_index(name='Outlet_IDs')
range_outlets['Outlet_Count'] = range_outlets['Outlet_IDs'].apply(len)

print(range_outlets)

  POI_Range                                         Outlet_IDs  Outlet_Count
0       0-2  [OUT_00001, OUT_00002, OUT_00003, OUT_00004, O...         16392
1       2-5  [OUT_00014, OUT_00048, OUT_00050, OUT_00054, O...          1863
2      5-10  [OUT_00013, OUT_00029, OUT_00032, OUT_00045, O...           830
3     10-20  [OUT_00040, OUT_00044, OUT_00074, OUT_00078, O...           400
4     20-30  [OUT_00374, OUT_00399, OUT_00442, OUT_00454, O...           156
5     30-40  [OUT_00026, OUT_00246, OUT_00262, OUT_00521, O...            77
6     40-50  [OUT_00010, OUT_00524, OUT_00876, OUT_00877, O...            26
7     50-60  [OUT_00303, OUT_01495, OUT_01784, OUT_01878, O...            15

In [64]:
Low_Potential_Hub =  range_outlets['Outlet_IDs'][0]
len(Low_Potential_Hub)

16392

In [63]:
Medium_Potential_Hub =  range_outlets['Outlet_IDs'][1]+range_outlets['Outlet_IDs'][2]
len(Medium_Potential_Hub)

2693

In [65]:
High_Potential_Hub =  range_outlets['Outlet_IDs'][3]+range_outlets['Outlet_IDs'][4]
Elite_Potential_Hub =  range_outlets['Outlet_IDs'][5]+range_outlets['Outlet_IDs'][6]+range_outlets['Outlet_IDs'][7]

In [69]:
print(len(High_Potential_Hub))
print(len(Elite_Potential_Hub))

556
118

In [67]:
pd.DataFrame(Low_Potential_Hub, columns=['Outlet_ID']).to_csv(r'Silver/Low_Potential_Hubs.csv', index=False)

In [68]:
pd.DataFrame(Medium_Potential_Hub, columns=['Outlet_ID']).to_csv(r'Silver/Medium_Potential_Hubs.csv', index=False)
pd.DataFrame(High_Potential_Hub, columns=['Outlet_ID']).to_csv(r'Silver/High_Potential_Hubs.csv', index=False)
pd.DataFrame(Elite_Potential_Hub, columns=['Outlet_ID']).to_csv(r'Silver/Elite_Potential_Hub.csv', index=False)

In [41]:
bins = [0,2,5, 10, 20, 30, 40, 50, 60]
labels = ['0-2','2-5','5-10' ,'10-20', '20-30', '30-40', '40-50', '50-60']

In [42]:
POI_dataDF['POI_Range'] = pd.cut(POI_dataDF['Total_POIs_1km'], bins=bins, labels=labels, right=False, include_lowest=True)

In [43]:
POI_dataDF = POI_dataDF.groupby('POI_Range')['Outlet_ID'].count().reset_index(name='Outlet_Count')

In [44]:
POI_dataDF

  POI_Range  Outlet_Count
0       0-2         16392
1       2-5          1863
2      5-10           830
3     10-20           400
4     20-30           156
5     30-40            77
6     40-50            26
7     50-60            15

In [49]:
POI_dataDF.columns = POI_dataDF.columns.str.strip()
print(POI_dataDF.columns.tolist())  # verify column names

['POI_Range', 'Outlet_Count']

In [51]:
range_outlets = POI_dataDF.groupby('POI_Range')['Outlet_ID'].apply(list).reset_index(name='Outlet_IDs')
range_outlets['Outlet_Count'] = range_outlets['Outlet_IDs'].apply(len)

print(range_outlets)

KeyError: 'Column not found: Outlet_ID'

In [45]:
mask = POI_dataDF['POI_Range'] == '0-2'

In [48]:
print(POI_dataDF[mask]['Outlet_ID'].tolist())

KeyError: 'Outlet_ID'