In [1]:
import pandas as pd

In [33]:
import pandas as pd
distributorDF = pd.read_csv('Bronze/distributor_seasonality_details.csv')

In [34]:
distributorDF.info()

<class 'pandas.DataFrame'>
RangeIndex: 360 entries, 0 to 359
Data columns (total 4 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Distributor_ID     360 non-null    str
 1   Year               360 non-null    int64
 2   Month              360 non-null    int64
 3   Seasonality_Index  360 non-null    str
dtypes: int64(2), str(2)
memory usage: 11.4 KB

In [35]:
distributorDF['year_month'] = distributorDF['Year'].astype(str) + '-' + distributorDF['Month'].astype(str).str.zfill(2)

In [36]:
distributorDF.head(10)

  Distributor_ID  Year  Month Seasonality_Index year_month
0      DIST_W_01  2023      1          Moderate    2023-01
1      DIST_W_01  2023      2          Moderate    2023-02
2      DIST_W_01  2023      3          Moderate    2023-03
3      DIST_W_01  2023      4         Favorable    2023-04
4      DIST_W_01  2023      5      Un-Favorable    2023-05
5      DIST_W_01  2023      6      Un-Favorable    2023-06
6      DIST_W_01  2023      7          Moderate    2023-07
7      DIST_W_01  2023      8          Moderate    2023-08
8      DIST_W_01  2023      9          Moderate    2023-09
9      DIST_W_01  2023     10          Moderate    2023-10

In [37]:
distributorDF = distributorDF.sort_values('year_month')

In [38]:
distributorDF.head(10)

    Distributor_ID  Year  Month Seasonality_Index year_month
0        DIST_W_01  2023      1          Moderate    2023-01
216     DIST_NW_01  2023      1          Moderate    2023-01
180      DIST_C_03  2023      1          Moderate    2023-01
288      DIST_S_01  2023      1         Favorable    2023-01
144      DIST_C_02  2023      1          Moderate    2023-01
108      DIST_C_01  2023      1          Moderate    2023-01
324      DIST_S_02  2023      1         Favorable    2023-01
72       DIST_W_03  2023      1          Moderate    2023-01
36       DIST_W_02  2023      1          Moderate    2023-01
252     DIST_NW_02  2023      1          Moderate    2023-01

In [39]:
distributorDF = distributorDF.drop(columns=['Year'])

In [40]:
distributorDF = distributorDF.drop(columns=['Month'])

In [41]:
cols = ['year_month', 'Distributor_ID', 'Seasonality_Index'] + [col for col in distributorDF.columns if col not in ['year_month', 'Distributor_ID', 'Seasonality_Index']]

In [42]:
distributorDF = distributorDF[cols]

In [43]:
distributorDF.to_csv(r'Silver/distributor_seasonality_details_by_clean.csv',index=False)

In [44]:
# HOLIDAY DAY DATA CLEANING
# --------------------------------------------------------------------------------

In [45]:
holidayDF = pd.read_csv('Bronze/holiday_list.csv')

In [46]:
holidayDF.head(10)

,Date,Holiday_Name,Holiday_Type
0,2023-01-06T00:00:00Z,Duruthu Full Moon Poya Day,Public
1,2023-01-15T00:00:00Z,Tamil Thai Pongal Day,Public
2,2023-01-16T00:00:00Z,Additional Holiday in lieu of Tamil Thai Ponga...,Public
3,2023-02-03T00:00:00Z,Additional Half Holiday in lieu of the Indepen...,Public
4,2023-02-04T00:00:00Z,National Day,Public
5,2023-02-05T00:00:00Z,Navam Full Moon Poya Day,Public
6,2024-03-24T00:00:00Z,Medin Full Moon Poya Day,Public
7,2023-03-06T00:00:00Z,Medin Full Moon Poya Day,Public
8,2023-04-05T00:00:00Z,Bak Full Moon Poya Day,Public
9,2023-04-07T00:00:00Z,Good Friday,Public

In [47]:
holidayDF['Date'] = pd.to_datetime(holidayDF['Date']).dt.date

In [48]:
holidayDF.head(10)

         Date                                       Holiday_Name Holiday_Type
0  2023-01-06                         Duruthu Full Moon Poya Day       Public
1  2023-01-15                              Tamil Thai Pongal Day       Public
2  2023-01-16  Additional Holiday in lieu of Tamil Thai Ponga...       Public
3  2023-02-03  Additional Half Holiday in lieu of the Indepen...       Public
4  2023-02-04                                       National Day       Public
5  2023-02-05                           Navam Full Moon Poya Day       Public
6  2024-03-24                           Medin Full Moon Poya Day       Public
7  2023-03-06                           Medin Full Moon Poya Day       Public
8  2023-04-05                             Bak Full Moon Poya Day       Public
9  2023-04-07                                        Good Friday       Public

In [49]:
holidayDF.info()

<class 'pandas.DataFrame'>
RangeIndex: 349 entries, 0 to 348
Data columns (total 3 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Date          349 non-null    object
 1   Holiday_Name  349 non-null    str
 2   Holiday_Type  349 non-null    str
dtypes: object(1), str(2)
memory usage: 8.3+ KB

In [50]:
holidayDF.to_csv(r'Silver/holiday_list_by_clean.csv',index=False)

In [2]:
trnasactionHistoryDF = pd.read_csv('Bronze/transactions_history_final.csv')

In [3]:
trnasactionHistoryDF.head(10)

,Outlet_ID,Year,Month,Distributor_ID,SKU_ID,Volume_Liters,Total_Bill_Value
0,OUT_19886,2024,12,DIST_S_02,SKU_10,5.897879,2177.632359
1,OUT_00837,2024,2,DIST_W_01,SKU_03,20.697364,7244.084814
2,OUT_15438,2025,12,DIST_NW_01,SKU_02,55.101801,13959.108787
3,OUT_12992,2025,1,DIST_C_01,SKU_07,24.063953,15641.548773
4,OUT_12334,2025,5,DIST_C_02,SKU_04,47.769665,15525.158656
5,OUT_06622,2025,12,DIST_W_02,SKU_08,8.442131,3714.516869
6,OUT_06220,2023,2,DIST_W_01,SKU_10,3.417114,1261.701912
7,OUT_18281,2023,10,DIST_S_02,SKU_09,6.642578,14613.706566
8,OUT_15347,2024,8,DIST_NW_02,SKU_04,6.109099,1985.480389
9,OUT_17437,2023,5,DIST_S_01,SKU_03,28.794869,10078.206589

In [4]:
trnasactionHistoryDF = trnasactionHistoryDF.drop(columns='Total_Bill_Value')

In [5]:
trnasactionHistoryDF = trnasactionHistoryDF.drop(columns='SKU_ID')

In [7]:
trnasactionHistoryDF['year_month'] = trnasactionHistoryDF['Year'].astype(str) + '-' + trnasactionHistoryDF['Month'].astype(str)

In [9]:
trnasactionHistoryDF = trnasactionHistoryDF.drop(columns='Year')

In [10]:
trnasactionHistoryDF = trnasactionHistoryDF.drop(columns='Month')

In [11]:
trnasactionHistoryDF.head(10)

   Outlet_ID Distributor_ID  Volume_Liters year_month
0  OUT_19886      DIST_S_02       5.897879    2024-12
1  OUT_00837      DIST_W_01      20.697364     2024-2
2  OUT_15438     DIST_NW_01      55.101801    2025-12
3  OUT_12992      DIST_C_01      24.063953     2025-1
4  OUT_12334      DIST_C_02      47.769665     2025-5
5  OUT_06622      DIST_W_02       8.442131    2025-12
6  OUT_06220      DIST_W_01       3.417114     2023-2
7  OUT_18281      DIST_S_02       6.642578    2023-10
8  OUT_15347     DIST_NW_02       6.109099     2024-8
9  OUT_17437      DIST_S_01      28.794869     2023-5

In [13]:
cols1 = ['Outlet_ID', 'year_month', 'Distributor_ID','Volume_Liters'] + [col for col in trnasactionHistoryDF.columns if col not in ['Outlet_ID', 'year_month', 'Distributor_ID','Volume_Liters']]

In [14]:
trnasactionHistoryDF = trnasactionHistoryDF[cols1]

In [15]:
trnasactionHistoryDF.head(10)

   Outlet_ID year_month Distributor_ID  Volume_Liters
0  OUT_19886    2024-12      DIST_S_02       5.897879
1  OUT_00837     2024-2      DIST_W_01      20.697364
2  OUT_15438    2025-12     DIST_NW_01      55.101801
3  OUT_12992     2025-1      DIST_C_01      24.063953
4  OUT_12334     2025-5      DIST_C_02      47.769665
5  OUT_06622    2025-12      DIST_W_02       8.442131
6  OUT_06220     2023-2      DIST_W_01       3.417114
7  OUT_18281    2023-10      DIST_S_02       6.642578
8  OUT_15347     2024-8     DIST_NW_02       6.109099
9  OUT_17437     2023-5      DIST_S_01      28.794869

In [26]:
trnasactionHistoryDF['year_month'] = pd.to_datetime(trnasactionHistoryDF['year_month'],format='%Y-%m')

In [27]:
trnasactionHistoryDF = trnasactionHistoryDF.sort_values(by=['Outlet_ID','year_month']).reset_index(drop = True)

In [28]:
trnasactionHistoryDF['year_month'] = trnasactionHistoryDF['year_month'].dt.strftime('%Y-%m')

In [29]:
trnasactionHistoryDF.head(20)

    Outlet_ID year_month Distributor_ID  Volume_Liters
0   OUT_00001    2023-03      DIST_W_03      60.511193
1   OUT_00001    2023-03      DIST_W_03      15.355303
2   OUT_00001    2023-03      DIST_W_03      63.132296
3   OUT_00001    2023-03      DIST_W_03      56.848981
4   OUT_00001    2023-03      DIST_W_03      24.765365
5   OUT_00001    2023-03      DIST_W_03      25.600579
6   OUT_00001    2023-03      DIST_W_03      56.402433
7   OUT_00001    2023-03      DIST_W_03     282.573656
8   OUT_00001    2023-03      DIST_W_03      31.527238
9   OUT_00001    2023-03      DIST_W_03      23.100382
10  OUT_00001    2023-03      DIST_W_03      16.425555
11  OUT_00001    2023-03      DIST_W_03      66.063092
12  OUT_00001    2023-03      DIST_W_03     104.803031
13  OUT_00001    2023-03      DIST_W_03      26.706679
14  OUT_00001    2023-03      DIST_W_03      18.665310
15  OUT_00001    2023-03      DIST_W_03      21.136352
16  OUT_00001    2023-03      DIST_W_03      24.669699
17  OUT_00001    2023-03      DIST_W_03      34.570480
18  OUT_00001    2023-03      DIST_W_03      20.966768
19  OUT_00001    2023-03      DIST_W_03      29.732770

In [30]:
trnasactionHistoryDF.to_csv(r'Silver/transactions_history_final_by_clean.csv',index=False)

In [31]:
trnasactionHistoryDF1 = trnasactionHistoryDF.drop(columns='Distributor_ID')

In [35]:
trnasactionHistoryDF1.head(10)

   Outlet_ID year_month  Volume_Liters
0  OUT_00001    2023-03      60.511193
1  OUT_00001    2023-03      15.355303
2  OUT_00001    2023-03      63.132296
3  OUT_00001    2023-03      56.848981
4  OUT_00001    2023-03      24.765365
5  OUT_00001    2023-03      25.600579
6  OUT_00001    2023-03      56.402433
7  OUT_00001    2023-03     282.573656
8  OUT_00001    2023-03      31.527238
9  OUT_00001    2023-03      23.100382

In [37]:
trnasactionHistoryDF1 = trnasactionHistoryDF1.groupby(['Outlet_ID','year_month'])['Volume_Liters'].sum().reset_index()

In [38]:
trnasactionHistoryDF1 = trnasactionHistoryDF1.sort_values(by=['Outlet_ID','year_month'])

In [42]:
trnasactionHistoryDF1 = trnasactionHistoryDF1.rename(
    columns={
        'Volume_Liters':'Volume_Liters_Sum'
    }
    )

In [43]:
trnasactionHistoryDF1.head(20)

    Outlet_ID year_month  Volume_Liters_Sum
0   OUT_00001    2023-03        1390.918670
1   OUT_00001    2023-06         382.687950
2   OUT_00001    2023-08         552.713934
3   OUT_00001    2023-10         541.861465
4   OUT_00001    2023-11         223.594015
5   OUT_00001    2024-03        1941.470001
6   OUT_00001    2024-05         350.532111
7   OUT_00001    2024-06         401.544922
8   OUT_00001    2024-07         248.414012
9   OUT_00001    2024-08         321.337314
10  OUT_00001    2024-09         304.603283
11  OUT_00001    2024-10         600.782008
12  OUT_00001    2024-11         598.819944
13  OUT_00001    2025-03        1402.731931
14  OUT_00001    2025-04         875.140680
15  OUT_00001    2025-05         397.626232
16  OUT_00001    2025-06         389.858736
17  OUT_00001    2025-07         639.922597
18  OUT_00001    2025-08         630.101322
19  OUT_00001    2025-09         654.893214

In [86]:
trnasactionHistoryDF1.to_csv(r'Silver/transactions_history_final_by_clean_totalSum_monthly.csv',index=False)

In [ ]:
# HOLIDAY COUNTS
# ----------------------------------------------------------------------------

In [74]:
holidayCountDF = pd.read_csv('Silver/holiday_list_by_clean.csv')

In [75]:
holidayCountDF.head(10)

         Date                Holiday_Name Holiday_Type
0  2023-01-06  Duruthu Full Moon Poya Day       Public
1  2023-01-06  Duruthu Full Moon Poya Day       Public
2  2023-01-06  Duruthu Full Moon Poya Day     Poya Day
3  2023-01-06  Duruthu Full Moon Poya Day   Mercantile
4  2023-01-06  Duruthu Full Moon Poya Day         Bank
5  2023-01-06  Duruthu Full Moon Poya Day     Poya Day
6  2023-01-06  Duruthu Full Moon Poya Day   Mercantile
7  2023-01-06  Duruthu Full Moon Poya Day         Bank
8  2023-01-15       Tamil Thai Pongal Day         Bank
9  2023-01-15       Tamil Thai Pongal Day   Mercantile

In [76]:
holidayCountDF = holidayCountDF.sort_values('Date')

In [77]:
holidayCountDF.head(10)

          Date                Holiday_Name Holiday_Type
0   2023-01-06  Duruthu Full Moon Poya Day       Public
1   2023-01-06  Duruthu Full Moon Poya Day       Public
2   2023-01-06  Duruthu Full Moon Poya Day     Poya Day
3   2023-01-06  Duruthu Full Moon Poya Day   Mercantile
4   2023-01-06  Duruthu Full Moon Poya Day         Bank
5   2023-01-06  Duruthu Full Moon Poya Day     Poya Day
6   2023-01-06  Duruthu Full Moon Poya Day   Mercantile
7   2023-01-06  Duruthu Full Moon Poya Day         Bank
13  2023-01-15       Tamil Thai Pongal Day         Bank
12  2023-01-15       Tamil Thai Pongal Day       Public

In [61]:
holidayCountDF.to_csv(r'Silver/holiday_list_by_sort.csv',index=False)

In [78]:
holidayCountDF['Date'] = pd.to_datetime(holidayCountDF['Date'])

In [ ]:
# holidayCountDF['year_month'] = holidayCountDF['Date'].dt.strftime('%Y-%m-%d')

In [79]:
holidayCountDF = holidayCountDF.groupby('Date')['Date'].nunique().reset_index(name='monthly_holiday_counts')

In [80]:
holidayCountDF.head(10)

        Date  monthly_holiday_counts
0 2023-01-06                       1
1 2023-01-15                       1
2 2023-01-16                       1
3 2023-02-03                       1
4 2023-02-04                       1
5 2023-02-05                       1
6 2023-03-06                       1
7 2023-04-05                       1
8 2023-04-07                       1
9 2023-04-13                       1

In [81]:
holidayCountDF['year_month'] = holidayCountDF['Date'].dt.strftime('%Y-%m')

In [82]:
holidayCountDF = holidayCountDF.groupby('year_month')['Date'].nunique().reset_index(name='monthly_holiday_count')

In [83]:
holidayCountDF = holidayCountDF.sort_values('year_month').reset_index(drop=True)

In [84]:
holidayCountDF.head(10)

  year_month  monthly_holiday_count
0    2023-01                      3
1    2023-02                      3
2    2023-03                      1
3    2023-04                      4
4    2023-05                      4
5    2023-06                      1
6    2023-07                      1
7    2023-08                      2
8    2023-09                      2
9    2023-10                      1

In [85]:
holidayCountDF.to_csv(r'Silver/holiday_list_by_clean.csv',index=False)